### ISSUE TITLE
Errors not resolving on re-save

### ISSUE THREAD

**Issue by altano** [blakeembrey/typescript-simple-loader#2]
I'm having a strange issue.  If you introduce an error while running webpack-dev-server, and then you fix the error, it usually resolves.  But this error isn't resolving:
1. repro here: https://github.com/altano/typescript-simple-loader-bug
2. npm i, npm start
3. builds fine
4. Remove "export default" in Note.ts
5. You'll get a warning/error `(1,18): File 'C:/src/typescript-simple-loader-bug/Note.ts' is not an external module.`
6. Undo your change, restoring Note.ts back to the buildable version
7. Save Note.ts
8. Note that you still get the same error, webpack-dev-server can't build the project.

At this point, if you restart webpack-dev-server it compiles fine.  Not sure what the issue is.

**Comment by blakeembrey** [comment]
![image](https://cloud.githubusercontent.com/assets/1088987/8529531/e79e487a-23cf-11e5-80d9-66f3e62f201e.png)

It seems to work correctly for me. I tried yesterday in a larger project and had no issues, and just got around to testing your example too. Do you have any more information on it? 

Edit: Really appreciated the example repo :+1:

**Comment by blakeembrey** [comment]
@altano I'm going to close this for now. Let me know if you're still having issues, I released a couple of new versions in the last few days - though the probably don't directly affect this.
